scoreboard objectives add gth.shoot_musket minecraft.used:minecraft.crossbow
scoreboard objectives add gth.shoot_longbow minecraft.used:minecraft.bow
scoreboard objectives add gth.musket_reload dummy
scoreboard objectives add gth.age dummy
scoreboard objectives add gth.sneaking minecraft.custom:minecraft.sneak_time
scoreboard objectives add gth.x1 dummy
scoreboard objectives add gth.y1 dummy
scoreboard objectives add gth.z1 dummy
scoreboard objectives add gth.x2 dummy
scoreboard objectives add gth.y2 dummy
scoreboard objectives add gth.z2 dummy
scoreboard objectives add gth.held_item dummy
scoreboard objectives add gth.arrow_damage dummy
scoreboard objectives add gth.longbow_cooldown dummy
scoreboard objectives add gth.buckler_cooldown dummy
scoreboard objectives add gth.horse_speed minecraft.custom:minecraft.horse_one_cm
scoreboard objectives add gth.block_damage minecraft.used:minecraft.shield
scoreboard objectives add gth.hold_buckler dummy
scoreboard objectives add gth.partisan_cooldown dummy
scoreboard objectives add gth.use_partisan minecraft.used:minecraft.carrot_on_a_stick